export class GenreEntry {
    name: string;
}

export const genreList: GenreEntry[] = [
    { name: 'Rock' },
    { name: 'Pop' },
    { name: 'Metal' },
    { name: 'Alternative' },
    { name: 'Alt. Country' },
    { name: 'Anime' },
    { name: 'Atmospheric Black Metal' },
    { name: 'Blues' },
    { name: 'Blues Rock' },
    { name: 'Christian' },
    { name: 'Classic Rock' },
    { name: 'Classical' },
    { name: 'Country' },
    { name: 'Crossover Thrash' },
    { name: 'Crust Punk' },
    { name: 'Dance' },
    { name: 'Death Metal' },
    { name: 'Deathcore' },
    { name: 'Desert Rock' },
    { name: 'Disco' },
    { name: 'Doom Metal' },
    { name: 'Djent' },
    { name: 'Dream Pop' },
    { name: 'Electronic' },
    { name: 'Electronica' },
    { name: 'Experimental' },
    { name: 'Folk' },
    { name: 'Folk Metal' },
    { name: 'Glam Metal' },
    { name: 'Gothic Rock' },
    { name: 'Grindcore' },
    { name: 'Hardcore' },
    { name: 'Hard Rock' },
    { name: 'Heavy Metal' },
    { name: 'Hip-Hop' },
    { name: 'Industrial' },
    { name: 'Instrumental' },
    { name: 'J-Pop' },
    { name: 'Jazz' },
    { name: 'K-Pop' },
    { name: 'Math Rock' },
    { name: 'Metalcore' },
    { name: 'Melodic Death Metal' },
    { name: 'Neo-classical' },
    { name: 'New Age' },
    { name: 'New Wave' },
    { name: 'Noise Rock' },
    { name: 'Noise' },
    { name: 'Nu Metal' },
    { name: 'NWOBHM' },
    { name: 'Oldies' },
    { name: 'Opera' },
    { name: 'Pagan Metal' },
    { name: 'Post-Hardcore' },
    { name: 'Post-Metal' },
    { name: 'Post-Punk' },
    { name: 'Post-Rock' },
    { name: 'Power Pop' },
    { name: 'Progressive Death Metal' },
    { name: 'Progressive Metal' },
    { name: 'Progressive Rock' },
    { name: 'Progressive' },
    { name: 'Punk' },
    { name: 'R&B' },
    { name: 'Rap' },
    { name: 'Rap Metal' },
    { name: 'Reggae' },
    { name: 'Rock & Roll' },
    { name: 'Rockabilly' },
    { name: 'Screamo' },
    { name: 'Shred' },
    { name: 'Singer-songwriter' },
    { name: 'Ska' },
    { name: 'Sludge' },
    { name: 'Soft Rock' },
    { name: 'Soul' },
    { name: 'Soundtrack' },
    { name: 'Speed Metal' },
    { name: 'Stoner' },
    { name: 'Surf' },
    { name: 'Swing' },
    { name: 'Symphonic Metal' },
    { name: 'Synthpop' },
    { name: 'Synthwave' },
    { name: 'Technical Death Metal' },
    { name: 'Thrash Metal' },
    { name: 'Trip-Hop' },
    { name: 'Viking Metal' },
    { name: 'World' },
    { name: 'Zydeco' },
];
