export class GenreEntry {
    name: string;
}

export const genreList: GenreEntry[] = [
    { name: 'Rock' },
    { name: 'Pop' },
    { name: 'Metal' },
    { name: 'Alternative' },
    { name: 'Anime' },
    { name: 'Blues' },
    { name: 'Classic Rock' },
    { name: 'Classical' },
    { name: 'Country' },
    { name: 'Dance' },
    { name: 'Death Metal' },
    { name: 'Deathcore' },
    { name: 'Disco' },
    { name: 'Djent' },
    { name: 'Electronic' },
    { name: 'Electronic' },
    { name: 'Electronica' },
    { name: 'Experimental' },
    { name: 'Folk' },
    { name: 'Gothic Rock' },
    { name: 'Hardcore' },
    { name: 'Heavy Metal' },
    { name: 'Hip-Hop' },
    { name: 'Industrial' },
    { name: 'Instrumental' },
    { name: 'J-Pop' },
    { name: 'Jazz' },
    { name: 'K-Pop' },
    { name: 'Math Rock' },
    { name: 'Metalcore' },
    { name: 'Neo-classical' },
    { name: 'New Age' },
    { name: 'New Wave' },
    { name: 'Noise Rock' },
    { name: 'Noise' },
    { name: 'NWOBHM' },
    { name: 'Oldies' },
    { name: 'Opera' },
    { name: 'Post-Hardcore' },
    { name: 'Post-Metal' },
    { name: 'Post-Punk' },
    { name: 'Post-Rock' },
    { name: 'Progressive Death Metal' },
    { name: 'Progressive Metal' },
    { name: 'Progressive Rock' },
    { name: 'Progressive' },
    { name: 'Punk' },
    { name: 'R&B' },
    { name: 'Rap' },
    { name: 'Reggae' },
    { name: 'Shred' },
    { name: 'Singer-songwriter' },
    { name: 'Ska' },
    { name: 'Sludge' },
    { name: 'Soul' },
    { name: 'Soundtrack' },
    { name: 'Symphonic Metal' },
    { name: 'Synthwave' },
    { name: 'Synthwave' },
    { name: 'Technical Death Metal' },
    { name: 'Thrash Metal' },
    { name: 'World' },
];
